### PR TITLE
Future proofing for sails v1

### LINKED ISSUE #27: Broke in upcoming sails v1
Sails v1 appears to have refactored the way modules get loaded thus the override to support multiples source paths for controller doesn't work anymore.
[This](https://github.com/balderdashy/sails/blob/master/lib/app/private/controller/load-action-modules.js) is the piece of code that now control actions loading.

One way to fix it may be to manually register actions using `sails.registerAction(action, identity)` for more info look [here](https://github.com/balderdashy/sails/blob/master/lib/app/private/controller/README.md).

### PR DESCRIPTION
**Pull request by edouardmenayde**
In an attempt to fix #27 I create this PR.

### CODE REVIEW

File: lib/app.js [hunk 1]
```diff
@@ -44,7 +45,20 @@ module.exports = {
...
+    const toLoad = ['policies'];
+
+    if (sails.registerAction) { // Test if it's sails v1 and use proper way to register actions from the authController
+      for (actionName in AuthController) {
+        if (AuthController.hasOwnProperty(actionName)) {
+          sails.registerAction(AuthController[actionName], 'auth/' + actionName);
+        }
+      }
+    }
+    else {
```
Comment (RWOverdijk) [inline lib/app.js]: else goes on same line as closing }

**Review by RWOverdijk — CHANGES_REQUESTED** [review]
Given information and your solution this code seems fine besides the CS.
